title: Infinity
author: Kameshwar Sharma  
email: kampower55@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is about the wonder you faces in your everyday life.
# social links
twitter_username: kameshwar18 # DO NOT include the @ character, or else the build will fail!
github_username:  kam2104 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
